import {
  IsString,
  IsOptional,
  IsNumber,
  IsUUID,
  IsBoolean,
  MinLength,
  MaxLength,
  Min,
  Matches,
} from 'class-validator';
import { Type } from 'class-transformer';

export class CreateProductClientPortalDto {
  // Product Definition
  @IsString()
  @MinLength(1, { message: 'اسم المنتج مطلوب' })
  @MaxLength(255)
  name: string;

  /** SKU is auto-generated by the system; ignored if sent from client */
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sku?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  description?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  category?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  brand?: string;

  // Logistics Information
  @IsNumber()
  @Min(0, { message: 'الوزن يجب أن يكون 0 أو أكثر' })
  @Type(() => Number)
  weight: number;

  @IsNumber()
  @Min(0, { message: 'الطول مطلوب' })
  @Type(() => Number)
  length: number;

  @IsNumber()
  @Min(0, { message: 'العرض مطلوب' })
  @Type(() => Number)
  width: number;

  @IsNumber()
  @Min(0, { message: 'الارتفاع مطلوب' })
  @Type(() => Number)
  height: number;

  @IsNumber()
  @Min(1, { message: 'الوحدات لكل كرتون مطلوبة' })
  @Type(() => Number)
  unitsPerCarton: number;

  // UOM for quantity (required for product)
  @IsUUID()
  defaultUomId: string;

  // Identification & Tracking (printable ASCII, max 100 chars)
  @IsOptional()
  @IsString()
  @MaxLength(100)
  @Matches(/^[\x20-\x7E]*$/, {
    message: 'تنسيق الباركود غير صالح',
  })
  barcode?: string;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  isSerialized?: boolean;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  isBatchTracked?: boolean;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  requiresExpiryDate?: boolean;

  // Inventory Rules
  @IsOptional()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  minThreshold?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  reorderPoint?: number;

  // Commercial Info
  @IsOptional()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  declaredValue?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  price?: number;
}
